<?php
/**
 * Script to Create Sample Data for Crowdfunding and B2B Marketplace
 * This script generates realistic sample data and downloads images
 */

require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';

set_time_limit(600);

// Sample users data
$sampleUsers = [
    ['name' => 'Sarah Kimani', 'email' => 'sarah.kimani@example.com', 'username' => 'sarahkimani'],
    ['name' => 'James Ochieng', 'email' => 'james.ochieng@example.com', 'username' => 'jamesochieng'],
    ['name' => 'Amina Hassan', 'email' => 'amina.hassan@example.com', 'username' => 'aminahassan'],
    ['name' => 'David Mwangi', 'email' => 'david.mwangi@example.com', 'username' => 'davidmwangi'],
    ['name' => 'Grace Wanjiku', 'email' => 'grace.wanjiku@example.com', 'username' => 'gracewanjiku'],
    ['name' => 'Peter Kipchoge', 'email' => 'peter.kipchoge@example.com', 'username' => 'peterkipchoge'],
    ['name' => 'Mary Njeri', 'email' => 'mary.njeri@example.com', 'username' => 'marynjeri'],
    ['name' => 'John Kamau', 'email' => 'john.kamau@example.com', 'username' => 'johnkamau'],
];

// Categories mapping
$categories = [
    1 => 'Technology & Software',
    2 => 'E-commerce & Retail',
    3 => 'Food & Beverage',
    4 => 'Manufacturing & Production',
    5 => 'Professional Services',
    6 => 'Real Estate & Construction',
    7 => 'Healthcare & Medical Business',
    8 => 'Education & Training Business',
    9 => 'Finance & Fintech',
    10 => 'Transportation & Logistics',
    11 => 'Marketing & Advertising',
    12 => 'Energy & Utilities',
    13 => 'Agriculture & Farming Business',
    14 => 'Hospitality & Tourism Business',
    15 => 'Media & Entertainment Business',
    16 => 'Consulting & Advisory',
    17 => 'Fashion & Apparel Business',
];

// Crowdfunding campaigns data
$campaigns = [
    // Technology & Software
    [
        'title' => 'AI-Powered Healthcare App for Rural Communities',
        'description' => 'Developing an innovative mobile application that uses artificial intelligence to provide healthcare consultations and medication reminders for rural communities in Kenya. The app will connect patients with qualified doctors via video calls and provide access to affordable healthcare services.',
        'goal' => 2500000,
        'location' => 'Nairobi, Kenya',
        'category_id' => 1,
        'image_url' => 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'E-Learning Platform for Primary Schools',
        'description' => 'Creating a comprehensive e-learning platform specifically designed for primary school students in Kenya. The platform will include interactive lessons, quizzes, and progress tracking to improve educational outcomes in underserved areas.',
        'goal' => 1800000,
        'location' => 'Mombasa, Kenya',
        'category_id' => 1,
        'image_url' => 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=600&fit=crop',
    ],
    // E-commerce & Retail
    [
        'title' => 'Online Marketplace for Local Artisans',
        'description' => 'Building an e-commerce platform to connect local artisans and craftspeople with customers across Africa. The platform will help preserve traditional crafts while providing income opportunities for talented artisans.',
        'goal' => 1500000,
        'location' => 'Kisumu, Kenya',
        'category_id' => 2,
        'image_url' => 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Sustainable Fashion Brand Launch',
        'description' => 'Launching an eco-friendly fashion brand that uses locally sourced materials and traditional African designs. The brand will create employment opportunities while promoting sustainable fashion practices.',
        'goal' => 2000000,
        'location' => 'Nairobi, Kenya',
        'category_id' => 2,
        'image_url' => 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=600&fit=crop',
    ],
    // Food & Beverage
    [
        'title' => 'Organic Farm Expansion Project',
        'description' => 'Expanding our organic farm to increase production of fresh vegetables and fruits. The project will create 50 new jobs and provide healthy, locally-grown produce to communities across Kenya.',
        'goal' => 3200000,
        'location' => 'Nakuru, Kenya',
        'category_id' => 3,
        'image_url' => 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Community Restaurant for Healthy Meals',
        'description' => 'Opening a community-focused restaurant that serves nutritious, affordable meals using locally sourced ingredients. The restaurant will also provide cooking classes and nutrition education.',
        'goal' => 1200000,
        'location' => 'Eldoret, Kenya',
        'category_id' => 3,
        'image_url' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=600&fit=crop',
    ],
    // Manufacturing & Production
    [
        'title' => 'Solar Panel Manufacturing Facility',
        'description' => 'Establishing a solar panel manufacturing facility to produce affordable renewable energy solutions for homes and businesses. This will help reduce energy costs and promote sustainable development.',
        'goal' => 5000000,
        'location' => 'Thika, Kenya',
        'category_id' => 4,
        'image_url' => 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Recycling Plant for Plastic Waste',
        'description' => 'Building a recycling plant to process plastic waste and create new products. This initiative will help reduce environmental pollution while creating employment opportunities.',
        'goal' => 4500000,
        'location' => 'Nairobi, Kenya',
        'category_id' => 4,
        'image_url' => 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&h=600&fit=crop',
    ],
    // Professional Services
    [
        'title' => 'Legal Aid Clinic for Low-Income Families',
        'description' => 'Establishing a legal aid clinic to provide free legal services to low-income families. The clinic will help people access justice and understand their legal rights.',
        'goal' => 800000,
        'location' => 'Nairobi, Kenya',
        'category_id' => 5,
        'image_url' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Accounting Services for Small Businesses',
        'description' => 'Creating a professional accounting firm to help small businesses manage their finances, file taxes, and grow their operations. We will provide affordable services tailored to local businesses.',
        'goal' => 1000000,
        'location' => 'Mombasa, Kenya',
        'category_id' => 5,
        'image_url' => 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=600&fit=crop',
    ],
    // Real Estate & Construction
    [
        'title' => 'Affordable Housing Development',
        'description' => 'Building affordable housing units for low and middle-income families. The project will provide quality homes with modern amenities at accessible prices.',
        'goal' => 15000000,
        'location' => 'Nairobi, Kenya',
        'category_id' => 6,
        'image_url' => 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Green Building Construction Company',
        'description' => 'Starting a construction company focused on eco-friendly building practices. We will use sustainable materials and energy-efficient designs to create environmentally responsible structures.',
        'goal' => 8000000,
        'location' => 'Kisumu, Kenya',
        'category_id' => 6,
        'image_url' => 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=800&h=600&fit=crop',
    ],
    // Healthcare & Medical
    [
        'title' => 'Mobile Health Clinic for Rural Areas',
        'description' => 'Launching a mobile health clinic that travels to rural communities providing free medical check-ups, vaccinations, and health education. The clinic will help improve healthcare access in underserved areas.',
        'goal' => 3500000,
        'location' => 'Narok, Kenya',
        'category_id' => 7,
        'image_url' => 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Mental Health Support Center',
        'description' => 'Establishing a mental health support center offering counseling, therapy, and support groups. The center will help reduce stigma around mental health and provide accessible care.',
        'goal' => 2200000,
        'location' => 'Nairobi, Kenya',
        'category_id' => 7,
        'image_url' => 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&h=600&fit=crop',
    ],
    // Education & Training
    [
        'title' => 'Vocational Training Center',
        'description' => 'Creating a vocational training center to teach practical skills like carpentry, plumbing, electrical work, and computer skills. The center will help youth gain employable skills.',
        'goal' => 2800000,
        'location' => 'Nakuru, Kenya',
        'category_id' => 8,
        'image_url' => 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Digital Skills Training Program',
        'description' => 'Launching a comprehensive digital skills training program for youth and adults. The program will teach coding, digital marketing, graphic design, and other in-demand tech skills.',
        'goal' => 1900000,
        'location' => 'Mombasa, Kenya',
        'category_id' => 8,
        'image_url' => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=600&fit=crop',
    ],
    // Finance & Fintech
    [
        'title' => 'Microfinance Platform for Small Businesses',
        'description' => 'Developing a digital microfinance platform that provides quick, affordable loans to small businesses and entrepreneurs. The platform will use innovative credit scoring to serve underserved markets.',
        'goal' => 4000000,
        'location' => 'Nairobi, Kenya',
        'category_id' => 9,
        'image_url' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Mobile Payment Solution for Farmers',
        'description' => 'Creating a mobile payment solution specifically designed for farmers to receive payments, access credit, and manage their finances. The solution will help improve financial inclusion in rural areas.',
        'goal' => 2600000,
        'location' => 'Eldoret, Kenya',
        'category_id' => 9,
        'image_url' => 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=600&fit=crop',
    ],
    // Transportation & Logistics
    [
        'title' => 'Electric Vehicle Fleet for Public Transport',
        'description' => 'Launching an electric vehicle fleet for public transportation to reduce carbon emissions and provide affordable, eco-friendly transport options. The fleet will include buses and vans.',
        'goal' => 12000000,
        'location' => 'Nairobi, Kenya',
        'category_id' => 10,
        'image_url' => 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Last-Mile Delivery Service',
        'description' => 'Starting a last-mile delivery service using motorcycles and bicycles for fast, affordable delivery in urban areas. The service will help small businesses reach customers efficiently.',
        'goal' => 1500000,
        'location' => 'Mombasa, Kenya',
        'category_id' => 10,
        'image_url' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop',
    ],
    // Marketing & Advertising
    [
        'title' => 'Digital Marketing Agency for SMEs',
        'description' => 'Establishing a digital marketing agency to help small and medium enterprises grow their online presence. We will provide social media management, SEO, and digital advertising services.',
        'goal' => 1100000,
        'location' => 'Nairobi, Kenya',
        'category_id' => 11,
        'image_url' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Content Creation Studio',
        'description' => 'Creating a professional content creation studio for video production, photography, and graphic design. The studio will serve businesses, creators, and organizations.',
        'goal' => 2400000,
        'location' => 'Kisumu, Kenya',
        'category_id' => 11,
        'image_url' => 'https://images.unsplash.com/photo-1493612276216-ee3925520721?w=800&h=600&fit=crop',
    ],
    // Energy & Utilities
    [
        'title' => 'Solar Power Installation Service',
        'description' => 'Starting a solar power installation service to help homes and businesses transition to renewable energy. We will provide affordable solar solutions with financing options.',
        'goal' => 3000000,
        'location' => 'Nakuru, Kenya',
        'category_id' => 12,
        'image_url' => 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Biogas Production from Organic Waste',
        'description' => 'Establishing a biogas production facility that converts organic waste into clean cooking gas. This will help reduce deforestation and provide affordable energy to communities.',
        'goal' => 3800000,
        'location' => 'Eldoret, Kenya',
        'category_id' => 12,
        'image_url' => 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&h=600&fit=crop',
    ],
    // Agriculture & Farming
    [
        'title' => 'Modern Poultry Farm Expansion',
        'description' => 'Expanding our modern poultry farm to increase egg and meat production. The expansion will create jobs and provide affordable protein to local communities.',
        'goal' => 4200000,
        'location' => 'Kiambu, Kenya',
        'category_id' => 13,
        'image_url' => 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Dairy Processing Plant',
        'description' => 'Building a dairy processing plant to produce milk, yogurt, and cheese from local farmers. The plant will help farmers get better prices and provide quality dairy products.',
        'goal' => 5500000,
        'location' => 'Narok, Kenya',
        'category_id' => 13,
        'image_url' => 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&h=600&fit=crop',
    ],
    // Hospitality & Tourism
    [
        'title' => 'Eco-Tourism Lodge Development',
        'description' => 'Developing an eco-tourism lodge that promotes sustainable tourism while preserving local culture and environment. The lodge will create employment and support local communities.',
        'goal' => 18000000,
        'location' => 'Maasai Mara, Kenya',
        'category_id' => 14,
        'image_url' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Cultural Experience Tour Company',
        'description' => 'Starting a tour company that offers authentic cultural experiences, connecting tourists with local communities. The company will promote cultural preservation and create income opportunities.',
        'goal' => 1600000,
        'location' => 'Lamu, Kenya',
        'category_id' => 14,
        'image_url' => 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&h=600&fit=crop',
    ],
    // Media & Entertainment
    [
        'title' => 'African Music Production Studio',
        'description' => 'Establishing a professional music production studio to support local artists and promote African music. The studio will provide recording, mixing, and mastering services.',
        'goal' => 3200000,
        'location' => 'Nairobi, Kenya',
        'category_id' => 15,
        'image_url' => 'https://images.unsplash.com/photo-1493612276216-ee3925520721?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Online Streaming Platform for African Content',
        'description' => 'Creating an online streaming platform dedicated to African movies, TV shows, and documentaries. The platform will showcase local talent and stories.',
        'goal' => 6000000,
        'location' => 'Nairobi, Kenya',
        'category_id' => 15,
        'image_url' => 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&h=600&fit=crop',
    ],
    // Consulting & Advisory
    [
        'title' => 'Business Consulting Firm for Startups',
        'description' => 'Establishing a consulting firm to help startups and small businesses with strategy, operations, and growth. We will provide affordable consulting services tailored to local markets.',
        'goal' => 900000,
        'location' => 'Nairobi, Kenya',
        'category_id' => 16,
        'image_url' => 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'HR Consulting Services',
        'description' => 'Creating an HR consulting firm to help businesses with recruitment, training, and human resource management. We will help companies build strong teams and improve workplace culture.',
        'goal' => 1300000,
        'location' => 'Mombasa, Kenya',
        'category_id' => 16,
        'image_url' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&h=600&fit=crop',
    ],
    // Fashion & Apparel
    [
        'title' => 'Sustainable Fashion Brand',
        'description' => 'Launching a sustainable fashion brand that uses eco-friendly materials and ethical production practices. The brand will create beautiful, affordable clothing while protecting the environment.',
        'goal' => 2100000,
        'location' => 'Nairobi, Kenya',
        'category_id' => 17,
        'image_url' => 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'African Print Clothing Line',
        'description' => 'Creating a clothing line that celebrates African prints and designs. The line will include modern, stylish pieces that incorporate traditional African patterns and fabrics.',
        'goal' => 1700000,
        'location' => 'Kisumu, Kenya',
        'category_id' => 17,
        'image_url' => 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800&h=600&fit=crop',
    ],
];

// B2B Marketplace listings data
$businessListings = [
    // Technology & Software
    [
        'title' => 'Established SaaS Platform for Small Businesses',
        'description' => 'Profitable SaaS platform serving 5,000+ small businesses across East Africa. Features include inventory management, accounting, and customer relationship management. Strong recurring revenue model with 95% customer retention rate.',
        'short_description' => 'Profitable SaaS platform with 5,000+ active users and strong recurring revenue.',
        'industry' => 'Technology & Software',
        'stage' => 'established',
        'location' => 'Nairobi, Kenya',
        'asking_price' => 45000000,
        'annual_revenue' => 12000000,
        'annual_profit' => 4800000,
        'years_in_business' => 5,
        'employees' => 25,
        'business_type' => 'B2B',
        'image_url' => 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Mobile App Development Company',
        'description' => 'Well-established mobile app development company with portfolio of 50+ successful apps. Team of 15 developers specializing in iOS and Android. Strong client relationships and proven track record.',
        'short_description' => 'Mobile app development company with 50+ successful apps and 15-person team.',
        'industry' => 'Technology & Software',
        'stage' => 'established',
        'location' => 'Mombasa, Kenya',
        'asking_price' => 28000000,
        'annual_revenue' => 8500000,
        'annual_profit' => 3200000,
        'years_in_business' => 4,
        'employees' => 15,
        'business_type' => 'B2B',
        'image_url' => 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&h=600&fit=crop',
    ],
    // E-commerce & Retail
    [
        'title' => 'Online Fashion Retail Store',
        'description' => 'Successful online fashion retail store with 20,000+ active customers. Strong social media presence and brand recognition. Inventory includes clothing, accessories, and footwear. Established supply chain and logistics.',
        'short_description' => 'Online fashion store with 20,000+ customers and strong brand presence.',
        'industry' => 'E-commerce & Retail',
        'stage' => 'established',
        'location' => 'Nairobi, Kenya',
        'asking_price' => 35000000,
        'annual_revenue' => 15000000,
        'annual_profit' => 5500000,
        'years_in_business' => 6,
        'employees' => 18,
        'business_type' => 'B2C',
        'image_url' => 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Electronics Retail Chain',
        'description' => 'Chain of 3 electronics retail stores in prime locations. Selling smartphones, laptops, accessories, and home appliances. Established supplier relationships and loyal customer base.',
        'short_description' => 'Electronics retail chain with 3 stores and strong supplier relationships.',
        'industry' => 'E-commerce & Retail',
        'stage' => 'established',
        'location' => 'Kisumu, Kenya',
        'asking_price' => 42000000,
        'annual_revenue' => 18000000,
        'annual_profit' => 6500000,
        'years_in_business' => 8,
        'employees' => 35,
        'business_type' => 'B2C',
        'image_url' => 'https://images.unsplash.com/photo-1556740758-90de374c12ad?w=800&h=600&fit=crop',
    ],
    // Food & Beverage
    [
        'title' => 'Popular Restaurant Chain',
        'description' => 'Well-known restaurant chain with 4 locations serving authentic African cuisine. Strong brand reputation, loyal customer base, and consistent profitability. Prime locations with high foot traffic.',
        'short_description' => 'Restaurant chain with 4 locations and strong brand reputation.',
        'industry' => 'Food & Beverage',
        'stage' => 'established',
        'location' => 'Nairobi, Kenya',
        'asking_price' => 55000000,
        'annual_revenue' => 22000000,
        'annual_profit' => 8800000,
        'years_in_business' => 10,
        'employees' => 60,
        'business_type' => 'B2C',
        'image_url' => 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Coffee Roasting and Distribution Business',
        'description' => 'Established coffee roasting business supplying premium coffee to cafes, restaurants, and retail stores. Direct relationships with local coffee farmers. Strong brand and growing market demand.',
        'short_description' => 'Coffee roasting business with direct farmer relationships and growing demand.',
        'industry' => 'Food & Beverage',
        'stage' => 'established',
        'location' => 'Nakuru, Kenya',
        'asking_price' => 32000000,
        'annual_revenue' => 12000000,
        'annual_profit' => 4800000,
        'years_in_business' => 7,
        'employees' => 22,
        'business_type' => 'B2B & B2C',
        'image_url' => 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&h=600&fit=crop',
    ],
    // Manufacturing & Production
    [
        'title' => 'Plastic Manufacturing Plant',
        'description' => 'Modern plastic manufacturing facility producing packaging materials, containers, and household items. State-of-the-art equipment, established customer base, and strong market position.',
        'short_description' => 'Plastic manufacturing plant with modern equipment and established customers.',
        'industry' => 'Manufacturing & Production',
        'stage' => 'established',
        'location' => 'Thika, Kenya',
        'asking_price' => 85000000,
        'annual_revenue' => 35000000,
        'annual_profit' => 14000000,
        'years_in_business' => 12,
        'employees' => 85,
        'business_type' => 'B2B',
        'image_url' => 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Textile Manufacturing Company',
        'description' => 'Textile manufacturing company producing fabrics for local and export markets. Modern production facilities, skilled workforce, and established distribution network. Strong growth potential.',
        'short_description' => 'Textile manufacturing with modern facilities and export capabilities.',
        'industry' => 'Manufacturing & Production',
        'stage' => 'established',
        'location' => 'Eldoret, Kenya',
        'asking_price' => 68000000,
        'annual_revenue' => 28000000,
        'annual_profit' => 11200000,
        'years_in_business' => 9,
        'employees' => 70,
        'business_type' => 'B2B',
        'image_url' => 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&h=600&fit=crop',
    ],
    // Professional Services
    [
        'title' => 'Accounting and Tax Services Firm',
        'description' => 'Established accounting firm serving 500+ clients including small businesses and individuals. Services include bookkeeping, tax preparation, financial consulting, and audit services. Strong reputation and recurring revenue.',
        'short_description' => 'Accounting firm with 500+ clients and strong recurring revenue.',
        'industry' => 'Professional Services',
        'stage' => 'established',
        'location' => 'Nairobi, Kenya',
        'asking_price' => 25000000,
        'annual_revenue' => 9500000,
        'annual_profit' => 3800000,
        'years_in_business' => 8,
        'employees' => 20,
        'business_type' => 'B2B',
        'image_url' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Legal Services Practice',
        'description' => 'Well-established law firm specializing in corporate law, commercial transactions, and business advisory. Team of 12 experienced lawyers serving corporate clients and high-net-worth individuals.',
        'short_description' => 'Law firm with 12 lawyers specializing in corporate and commercial law.',
        'industry' => 'Professional Services',
        'stage' => 'established',
        'location' => 'Mombasa, Kenya',
        'asking_price' => 38000000,
        'annual_revenue' => 15000000,
        'annual_profit' => 6000000,
        'years_in_business' => 11,
        'employees' => 12,
        'business_type' => 'B2B',
        'image_url' => 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=600&fit=crop',
    ],
    // Real Estate & Construction
    [
        'title' => 'Real Estate Development Company',
        'description' => 'Established real estate development company with portfolio of residential and commercial projects. Strong track record, experienced team, and valuable land assets. Multiple projects in pipeline.',
        'short_description' => 'Real estate developer with strong portfolio and valuable land assets.',
        'industry' => 'Real Estate & Construction',
        'stage' => 'established',
        'location' => 'Nairobi, Kenya',
        'asking_price' => 120000000,
        'annual_revenue' => 45000000,
        'annual_profit' => 18000000,
        'years_in_business' => 15,
        'employees' => 45,
        'business_type' => 'B2C',
        'image_url' => 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Construction Materials Supply Business',
        'description' => 'Wholesale supplier of construction materials including cement, steel, timber, and hardware. Established relationships with major construction companies. Strong cash flow and inventory management.',
        'short_description' => 'Construction materials supplier with established contractor relationships.',
        'industry' => 'Real Estate & Construction',
        'stage' => 'established',
        'location' => 'Nakuru, Kenya',
        'asking_price' => 48000000,
        'annual_revenue' => 20000000,
        'annual_profit' => 8000000,
        'years_in_business' => 10,
        'employees' => 30,
        'business_type' => 'B2B',
        'image_url' => 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=800&h=600&fit=crop',
    ],
    // Healthcare & Medical
    [
        'title' => 'Private Medical Clinic',
        'description' => 'Well-equipped private medical clinic offering general practice, specialist consultations, and diagnostic services. Modern facilities, experienced medical staff, and strong patient base. Prime location.',
        'short_description' => 'Private medical clinic with modern facilities and experienced staff.',
        'industry' => 'Healthcare & Medical Business',
        'stage' => 'established',
        'location' => 'Nairobi, Kenya',
        'asking_price' => 65000000,
        'annual_revenue' => 25000000,
        'annual_profit' => 10000000,
        'years_in_business' => 12,
        'employees' => 28,
        'business_type' => 'B2C',
        'image_url' => 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Pharmacy Chain',
        'description' => 'Chain of 5 pharmacies in strategic locations. Well-stocked inventory, licensed operations, and loyal customer base. Strong relationships with pharmaceutical suppliers and insurance companies.',
        'short_description' => 'Pharmacy chain with 5 locations and strong supplier relationships.',
        'industry' => 'Healthcare & Medical Business',
        'stage' => 'established',
        'location' => 'Mombasa, Kenya',
        'asking_price' => 72000000,
        'annual_revenue' => 28000000,
        'annual_profit' => 11200000,
        'years_in_business' => 14,
        'employees' => 40,
        'business_type' => 'B2C',
        'image_url' => 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=800&h=600&fit=crop',
    ],
    // Education & Training
    [
        'title' => 'Private School Network',
        'description' => 'Network of 3 private schools offering quality education from primary to secondary level. Strong academic performance, experienced teachers, and modern facilities. Established reputation.',
        'short_description' => 'Private school network with 3 schools and strong academic reputation.',
        'industry' => 'Education & Training Business',
        'stage' => 'established',
        'location' => 'Nairobi, Kenya',
        'asking_price' => 95000000,
        'annual_revenue' => 38000000,
        'annual_profit' => 15200000,
        'years_in_business' => 16,
        'employees' => 120,
        'business_type' => 'B2C',
        'image_url' => 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Professional Training Institute',
        'description' => 'Vocational training institute offering courses in IT, business, hospitality, and technical skills. Accredited programs, experienced instructors, and strong job placement record.',
        'short_description' => 'Vocational training institute with accredited programs and strong placement record.',
        'industry' => 'Education & Training Business',
        'stage' => 'established',
        'location' => 'Kisumu, Kenya',
        'asking_price' => 42000000,
        'annual_revenue' => 16000000,
        'annual_profit' => 6400000,
        'years_in_business' => 9,
        'employees' => 35,
        'business_type' => 'B2C',
        'image_url' => 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=600&fit=crop',
    ],
    // Finance & Fintech
    [
        'title' => 'Microfinance Institution',
        'description' => 'Licensed microfinance institution serving small businesses and individuals. Strong loan portfolio, low default rates, and profitable operations. Growing customer base and expansion opportunities.',
        'short_description' => 'Microfinance institution with strong portfolio and profitable operations.',
        'industry' => 'Finance & Fintech',
        'stage' => 'established',
        'location' => 'Nairobi, Kenya',
        'asking_price' => 150000000,
        'annual_revenue' => 60000000,
        'annual_profit' => 24000000,
        'years_in_business' => 18,
        'employees' => 65,
        'business_type' => 'B2C',
        'image_url' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Payment Processing Platform',
        'description' => 'Established payment processing platform serving merchants and businesses. Integrated with major banks and mobile money providers. Strong transaction volume and recurring revenue model.',
        'short_description' => 'Payment processing platform with strong transaction volume and bank integrations.',
        'industry' => 'Finance & Fintech',
        'stage' => 'established',
        'location' => 'Nairobi, Kenya',
        'asking_price' => 180000000,
        'annual_revenue' => 72000000,
        'annual_profit' => 28800000,
        'years_in_business' => 7,
        'employees' => 55,
        'business_type' => 'B2B',
        'image_url' => 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=600&fit=crop',
    ],
    // Transportation & Logistics
    [
        'title' => 'Logistics and Freight Company',
        'description' => 'Established logistics company providing freight, warehousing, and distribution services. Fleet of 25 vehicles, warehouse facilities, and established client relationships. Strong market position.',
        'short_description' => 'Logistics company with 25-vehicle fleet and warehouse facilities.',
        'industry' => 'Transportation & Logistics',
        'stage' => 'established',
        'location' => 'Nairobi, Kenya',
        'asking_price' => 88000000,
        'annual_revenue' => 35000000,
        'annual_profit' => 14000000,
        'years_in_business' => 11,
        'employees' => 75,
        'business_type' => 'B2B',
        'image_url' => 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Taxi and Ride-Hailing Service',
        'description' => 'Established taxi and ride-hailing service with fleet of 50 vehicles and mobile app. Strong brand recognition, loyal customer base, and profitable operations. Expansion opportunities available.',
        'short_description' => 'Ride-hailing service with 50-vehicle fleet and mobile app.',
        'industry' => 'Transportation & Logistics',
        'stage' => 'established',
        'location' => 'Mombasa, Kenya',
        'asking_price' => 55000000,
        'annual_revenue' => 22000000,
        'annual_profit' => 8800000,
        'years_in_business' => 6,
        'employees' => 45,
        'business_type' => 'B2C',
        'image_url' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop',
    ],
    // Marketing & Advertising
    [
        'title' => 'Full-Service Marketing Agency',
        'description' => 'Comprehensive marketing agency offering digital marketing, branding, advertising, and PR services. Portfolio of 200+ successful campaigns, strong client relationships, and creative team.',
        'short_description' => 'Marketing agency with 200+ campaigns and comprehensive service offerings.',
        'industry' => 'Marketing & Advertising',
        'stage' => 'established',
        'location' => 'Nairobi, Kenya',
        'asking_price' => 32000000,
        'annual_revenue' => 12000000,
        'annual_profit' => 4800000,
        'years_in_business' => 8,
        'employees' => 28,
        'business_type' => 'B2B',
        'image_url' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Digital Advertising Platform',
        'description' => 'Digital advertising platform connecting advertisers with publishers. Proprietary technology, strong advertiser base, and growing revenue. Scalable business model with expansion potential.',
        'short_description' => 'Digital advertising platform with proprietary technology and growing revenue.',
        'industry' => 'Marketing & Advertising',
        'stage' => 'early',
        'location' => 'Nairobi, Kenya',
        'asking_price' => 25000000,
        'annual_revenue' => 8500000,
        'annual_profit' => 3200000,
        'years_in_business' => 3,
        'employees' => 18,
        'business_type' => 'B2B',
        'image_url' => 'https://images.unsplash.com/photo-1493612276216-ee3925520721?w=800&h=600&fit=crop',
    ],
    // Energy & Utilities
    [
        'title' => 'Solar Energy Installation Company',
        'description' => 'Established solar energy company providing installation, maintenance, and consulting services. Strong track record, experienced team, and growing market demand. Multiple commercial and residential projects.',
        'short_description' => 'Solar energy company with strong track record and growing demand.',
        'industry' => 'Energy & Utilities',
        'stage' => 'established',
        'location' => 'Nakuru, Kenya',
        'asking_price' => 45000000,
        'annual_revenue' => 18000000,
        'annual_profit' => 7200000,
        'years_in_business' => 7,
        'employees' => 32,
        'business_type' => 'B2B & B2C',
        'image_url' => 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Water Purification and Distribution',
        'description' => 'Water purification and distribution business serving residential and commercial customers. Modern filtration systems, established customer base, and recurring revenue model.',
        'short_description' => 'Water purification business with modern systems and recurring revenue.',
        'industry' => 'Energy & Utilities',
        'stage' => 'established',
        'location' => 'Eldoret, Kenya',
        'asking_price' => 38000000,
        'annual_revenue' => 15000000,
        'annual_profit' => 6000000,
        'years_in_business' => 9,
        'employees' => 25,
        'business_type' => 'B2C',
        'image_url' => 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&h=600&fit=crop',
    ],
    // Agriculture & Farming
    [
        'title' => 'Large-Scale Commercial Farm',
        'description' => 'Commercial farm producing maize, wheat, and vegetables on 500 acres. Modern irrigation systems, mechanized equipment, and established market channels. Strong profitability and growth potential.',
        'short_description' => 'Commercial farm on 500 acres with modern equipment and established markets.',
        'industry' => 'Agriculture & Farming Business',
        'stage' => 'established',
        'location' => 'Narok, Kenya',
        'asking_price' => 120000000,
        'annual_revenue' => 48000000,
        'annual_profit' => 19200000,
        'years_in_business' => 20,
        'employees' => 95,
        'business_type' => 'B2B',
        'image_url' => 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Dairy Farm and Processing',
        'description' => 'Integrated dairy operation with 200 dairy cows, processing facility, and distribution network. Producing milk, yogurt, and cheese. Strong brand and market presence.',
        'short_description' => 'Integrated dairy operation with 200 cows and processing facility.',
        'industry' => 'Agriculture & Farming Business',
        'stage' => 'established',
        'location' => 'Kiambu, Kenya',
        'asking_price' => 75000000,
        'annual_revenue' => 30000000,
        'annual_profit' => 12000000,
        'years_in_business' => 15,
        'employees' => 50,
        'business_type' => 'B2B & B2C',
        'image_url' => 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&h=600&fit=crop',
    ],
    // Hospitality & Tourism
    [
        'title' => 'Boutique Hotel Chain',
        'description' => 'Chain of 3 boutique hotels in prime tourist locations. Unique design, excellent service, and strong online presence. High occupancy rates and loyal customer base.',
        'short_description' => 'Boutique hotel chain with 3 properties and strong online presence.',
        'industry' => 'Hospitality & Tourism Business',
        'stage' => 'established',
        'location' => 'Maasai Mara, Kenya',
        'asking_price' => 180000000,
        'annual_revenue' => 72000000,
        'annual_profit' => 28800000,
        'years_in_business' => 12,
        'employees' => 85,
        'business_type' => 'B2C',
        'image_url' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Safari Tour Operator',
        'description' => 'Established safari tour operator offering wildlife tours, cultural experiences, and adventure activities. Strong relationships with lodges, experienced guides, and excellent customer reviews.',
        'short_description' => 'Safari tour operator with strong lodge relationships and excellent reviews.',
        'industry' => 'Hospitality & Tourism Business',
        'stage' => 'established',
        'location' => 'Nairobi, Kenya',
        'asking_price' => 42000000,
        'annual_revenue' => 16000000,
        'annual_profit' => 6400000,
        'years_in_business' => 10,
        'employees' => 30,
        'business_type' => 'B2C',
        'image_url' => 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&h=600&fit=crop',
    ],
    // Media & Entertainment
    [
        'title' => 'Music Production and Record Label',
        'description' => 'Established music production studio and record label with roster of successful artists. State-of-the-art recording facilities, experienced producers, and strong industry connections.',
        'short_description' => 'Music production studio and record label with successful artist roster.',
        'industry' => 'Media & Entertainment Business',
        'stage' => 'established',
        'location' => 'Nairobi, Kenya',
        'asking_price' => 35000000,
        'annual_revenue' => 14000000,
        'annual_profit' => 5600000,
        'years_in_business' => 8,
        'employees' => 22,
        'business_type' => 'B2B',
        'image_url' => 'https://images.unsplash.com/photo-1493612276216-ee3925520721?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Event Management and Production Company',
        'description' => 'Full-service event management company organizing concerts, corporate events, and festivals. Strong vendor relationships, experienced team, and excellent reputation in the industry.',
        'short_description' => 'Event management company with strong vendor relationships and industry reputation.',
        'industry' => 'Media & Entertainment Business',
        'stage' => 'established',
        'location' => 'Mombasa, Kenya',
        'asking_price' => 28000000,
        'annual_revenue' => 11000000,
        'annual_profit' => 4400000,
        'years_in_business' => 6,
        'employees' => 20,
        'business_type' => 'B2B',
        'image_url' => 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&h=600&fit=crop',
    ],
    // Consulting & Advisory
    [
        'title' => 'Management Consulting Firm',
        'description' => 'Established management consulting firm serving SMEs and corporations. Services include strategy, operations, HR, and financial consulting. Strong client portfolio and experienced consultants.',
        'short_description' => 'Management consulting firm with strong client portfolio and experienced team.',
        'industry' => 'Consulting & Advisory',
        'stage' => 'established',
        'location' => 'Nairobi, Kenya',
        'asking_price' => 38000000,
        'annual_revenue' => 15000000,
        'annual_profit' => 6000000,
        'years_in_business' => 10,
        'employees' => 25,
        'business_type' => 'B2B',
        'image_url' => 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'IT Consulting and Solutions Provider',
        'description' => 'IT consulting firm providing technology solutions, system integration, and IT support services. Strong technical expertise, established client base, and recurring revenue from support contracts.',
        'short_description' => 'IT consulting firm with strong technical expertise and recurring revenue.',
        'industry' => 'Consulting & Advisory',
        'stage' => 'established',
        'location' => 'Nairobi, Kenya',
        'asking_price' => 32000000,
        'annual_revenue' => 12500000,
        'annual_profit' => 5000000,
        'years_in_business' => 7,
        'employees' => 18,
        'business_type' => 'B2B',
        'image_url' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&h=600&fit=crop',
    ],
    // Fashion & Apparel
    [
        'title' => 'Fashion Design and Manufacturing',
        'description' => 'Fashion design company creating contemporary African-inspired clothing. Design studio, manufacturing facility, and retail outlets. Strong brand identity and growing customer base.',
        'short_description' => 'Fashion design company with manufacturing facility and retail outlets.',
        'industry' => 'Fashion & Apparel Business',
        'stage' => 'established',
        'location' => 'Nairobi, Kenya',
        'asking_price' => 45000000,
        'annual_revenue' => 18000000,
        'annual_profit' => 7200000,
        'years_in_business' => 9,
        'employees' => 40,
        'business_type' => 'B2C',
        'image_url' => 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=600&fit=crop',
    ],
    [
        'title' => 'Footwear Manufacturing and Retail',
        'description' => 'Footwear manufacturing company producing quality shoes and sandals. Manufacturing facility, retail stores, and wholesale distribution. Established brand and strong market presence.',
        'short_description' => 'Footwear manufacturer with retail stores and wholesale distribution.',
        'industry' => 'Fashion & Apparel Business',
        'stage' => 'established',
        'location' => 'Kisumu, Kenya',
        'asking_price' => 38000000,
        'annual_revenue' => 15000000,
        'annual_profit' => 6000000,
        'years_in_business' => 11,
        'employees' => 35,
        'business_type' => 'B2B & B2C',
        'image_url' => 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800&h=600&fit=crop',
    ],
];

echo "Sample data arrays created. Total campaigns: " . count($campaigns) . ", Total business listings: " . count($businessListings) . "\n";
